blank_issues_enabled: false
contact_links:
  - name: 🤔 Troubleshooting
    url: https://firebase-php.readthedocs.io/en/6.x/troubleshooting.html
    about: Please check the troubleshooting section of the documentation for commonly known problems.
  - name: ❤️ Sponsor this project
    url: https://github.com/sponsors/jeromegamez
    about: Support the continued maintenance and support of this project by becoming a GitHub Sponsor. Check the Sponsors page to see which tier entitles you for extended support.
