name: 💫 Feature request
description: Propose a new feature.
labels:
  - feature-request
assignees:
  - jeromegamez
body:
  - type: markdown
    attributes:
      value: |
        ### Important note

        This issue form is for feature requests only. Please provide as much information as possible. If your feature request refers to existing functionality in other Firebase Admin SDKs, please include links to the relevant documentation and code.

        Requests for features that are usually only available in Client SDKs are usually considered out of scope of this SDK.
  - type: textarea
    attributes:
      label: Describe the feature you would like to see
    validations:
      required: true
